default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: localhost

development:
  <<: *default
  database: odds_media_hub_development 
  username: bhuwadol.odds
  password: your_password 

test:
  <<: *default
  database: odds_media_hub_test   
  username: bhuwadol.odds
  password: your_password 

production:
  primary: &primary_production
    <<: *default
    database: odds_media_hub_production  # Change to odds_media_hub
    username: odds_media_hub_user        # Change to your preferred username
    password: <%= ENV["DB_PASSWORD"] %>  # Update with your environment variable for production password
  cache:
    <<: *primary_production
    database: odds_media_hub_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: odds_media_hub_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: odds_media_hub_production_cable
    migrations_paths: db/cable_migrate
